### ISSUE TITLE
How can I use the viewmode utility widget in Sequencer?

### ISSUE THREAD

**Issue by HoneyHiveStudios** [Ares9323/AdvancedEditorUtilities#1]
Hello there! So I've been trying to render a scene using the wireframe mode. So I bought your plugin to simplify my task. But I can't seem to do it. Do you know of any way to render a scene in the wireframe mode? A quick response would be helpful. Thanks!

**Comment by Ares9323** [comment]
Hi! Are you trying to do it in the sequencer?
If that's the case it should be enough to run the command "viewmode wireframe" in a "Execute console command" node in the Event BeginPlay 
![image](https://github.com/Ares9323/AdvancedEditorUtilities/assets/46932745/2d14bdbe-d089-4f06-a6d0-fc625d184f54)

**Comment by HoneyHiveStudios** [comment]
Thank you for the quick reply, but unfortunately the cine cam is still rendering in the lit mode.

**Comment by Ares9323** [comment]
Right now I'm at work, I'll try to test it as soon as possible, it must be an issue with the CineCameraComponent or with the sequencer.

**Comment by HoneyHiveStudios** [comment]
Thanks, I really appreciate your quick support

**Comment by Ares9323** [comment]
I think I was able to fix it:
![image](https://github.com/Ares9323/AdvancedEditorUtilities/assets/46932745/794d46bf-e2fe-4218-888c-d3190b0bc2f9)

You need to call the command inside the CineCameraActor, to do this you have to select it in the outliner, and click the "Blueprint/Add Script" button:
![image](https://github.com/Ares9323/AdvancedEditorUtilities/assets/46932745/21032c83-fc0a-4876-80a3-7b6a007379b2)

Then insert the console command node in the event graph:
![image](https://github.com/Ares9323/AdvancedEditorUtilities/assets/46932745/c8baf842-6e92-4db7-9a6a-8c3521ca6040)

Since you changed the actor, references in the level sequence could be probably broken, replace the CineCameraActor with the new one: 
![image](https://github.com/Ares9323/AdvancedEditorUtilities/assets/46932745/9e198f89-78f2-44b9-9c06-c3aa5ed0288b)



I hope this solves your issue and I also hope that you will enjoy the plugin in the future, even if in this case it was not useful to you!

Let me know if it works, have a nice day!

**Comment by HoneyHiveStudios** [comment]
Hello there, unfortunately your method doesn't seem to work. Maybe cause that is somehow patched in UE5?

**Comment by Ares9323** [comment]
I've just tried it in 5.2 and it works, there's even an easier way to do it:

- Add a blueprint script component to the camera:
![image](https://github.com/Ares9323/AdvancedEditorUtilities/assets/46932745/3e085734-eccb-4a8b-8554-5b5cf05debfa)

- Choose actor compoent and give it the name you prefer:
![image](https://github.com/Ares9323/AdvancedEditorUtilities/assets/46932745/ec3b688b-8ce2-4e30-95ca-9d8971bcf319)

- Launch the console command in the event graph 
![image](https://github.com/Ares9323/AdvancedEditorUtilities/assets/46932745/97b2a601-6eb3-45a8-ba5b-5ff83ea7dc41)

- No need to fix stuff in the sequencer 'cause you didn't change the actor but just added a component

**Comment by Ares9323** [comment]
@HoneyHiveStudios Were you able to solve your issue? May I close this issue?
